const ActionTypes = {
  GENRE_LOADING: "GENRE_LOADING",
  GENRE_ERROR: "GENRE_ERROR",
  GENRE_SUCCESS: "GENRE_SUCCESS",
  MODAL_OPEN: "MODAL_OPEN",
  MODAL_CLOSE: "MODAL_CLOSE",
  MOVIE_LOADING: "MOVIE_LOADING",
  MOVIE_ERROR: "MOVIE_ERROR",
  MOVIE_SUCCESS: "MOVIE_SUCCESS",
  WATCHLIST_LOADING: "WATCHLIST_LOADING",
  WATCHLIST_ERROR: "WATCHLIST_ERROR",
  WATCHLIST_SUCCESS: "WATCHLIST_SUCCESS",
  WATCHLIST_ADD: "WATCHLIST_ADD",
  WATCHLIST_REMOVE: "WATCHLIST_REMOVE",
};
export default ActionTypes;
